default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: blooming
  pool: 5
  username: kiplangat
  password: 71765543   ### password you have specified within psql
  host: localhost
  port: 5432  

test:
  <<: *default
  url: "postgresql://kiplangat:71765543@localhost:5432/blooming"

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>